server:
  port: 8888
spring:
  application:
    name: ms-admin-config-server
#Configuracion Local
  profiles:
    active: git
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///C:\Users\Noodlexz\Documents\GitHub\Micross-gateway\ms-admin-server-data
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Los-f5/admin-data
          username: anllacarpo@gmail.com
          password: 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
          clone-on-start: true
#          force-pull: true
#          timeout: 5
